services:
- docker
env:
  global:
  - TERM=dumb
  - DOCKER_USERNAME=daggerok
  - DOCKER_IMAGE_NAME=jboss
  - secure: EEEA8Ut61xCAv1wDRXSY9I1FKLhRYGUvXIqYqX3YD1sGM+mKxDZCc6WXio20QdXBKU0zBAEbh1VbB+lQDjXNrFT4DV54QbuJCkz01sbvYHEfT9O0VjPXxShZdW2ngdpQP00Ghbpcs0SX28duoRdzjDIc+wFK6DH7zIfsqCnl3isrKazd9cinhnRvmU2tIhZIRk8jX3XYm2+It71vnyRl7xiDbymy+mitoErPV8PXRamzaBFrRbkB+NZ6O+J7H5S/F78XQ+ThV7BA/HxUCJ2lTzfY2x7MBNunqlVJL+3MdJrXg61r1TXiBvjsQ0IUnTV3mzt1RlQYnoE8BPbkWsdhulGxGJGmjBt/BStwvGTcaagSHW0afb4cZeAKV74jZbNdnv6/TuQPNLFBNM54pp9muJe5NzI5DadSKU+hIbNe84D0Qj0J5kPF2rHpCcb8Cy90nSpjslj4altBXuuKET3P1r3alyMCS9pwzbIy/FYhLDGlknJ3zgs4ADigLiZznTSvnyABzCn64aipccegCN8U7vEYzCxhSwWzuQZtxdS325n5CgvHy/p8WyKYBFpSiLjbyrm4f/WGqZHvJU6Xz9wGch3Vh/nI6yAEHpns8wGujYhFhLo0eLr2ELgHtRq49krQewj/F7t2YF2WySPDU1EpoCj3XVE/4zfeATksoRw0khY=
install: true
script:
- docker build -t ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} .
- |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest-alpine
  elif [ "${TRAVIS_BRANCH}" == "4.2.3.GA-java1.5" ]; then
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:ubuntu
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}-ubuntu
  else
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}-alpine
  fi
- echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
- docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}
