services:
- docker
env:
  global:
  - TERM=dumb
  - DOCKER_USERNAME=daggerok
  - DOCKER_IMAGE_NAME=jboss4
  - secure: KsPWTLnm7tnzlZz6ymuSu4zN7ndoaI+ensmSnSgXk/uzuO/gYih1FiJ/1kgQxPun3WdHoJJamzQt6t7rXYEh5YpUzZ8cIQf4oitnU5VQ13hYwjc73eLwldt3np8L2kxjUlBX9Nr3q3BEmGrOh7TGFz0Du9vnikJ4/DpYHyRoJZR7NxKIZkdSfBdHeVbYYqSY0AY3+El05IK6Hk4L5PEPt57pm09l0Mv48QgJ8soEy2k0Q4dIM9rjILf3k1X3MsCSHokwVmQ7fbrs9309p8SQ8r43DjOv6xL1YDb2Ow+meO214ZUJGh8ZamTdZ6w+WRkZWX4aAfKCsuMoQRhNDiZ/Oo/5OR7nWWqJHZgU2L0OdRrZV+AAzh86BiFM9Uv4kI2IIuuUysx5E1hnpUntWbnXaJGO68GWSWA6XUnPn/XIJzBP10VypZh6f84VSDOb46UNZMnfzi93DySYNcsaI6SCiaiytPykZdeNFApqXzfFAseItJuvqytRiTjOmGpctTwiWCwMpQadsbQUlX51U7kuKueCYiQw1+jR5xLFys1S1GqSjNCIjPoCXTYiJgANx/ivy+xshJUAQmGPgpqE6/jk61OMpdRP9KOO8yeVZCuLYWi5Gx2wLTGZ97JsajkGDoWG4vMVMvQPiE0QQVJPwI2EOMkZmZJlp0QmofjNEsdaCMM=
script:
- docker build -t ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} .
- |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:alpine
  else
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}-alpine
  fi
- docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
- docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}

