services:
- docker
env:
  global:
  - TERM=dumb
  - DOCKER_USERNAME=daggerok
  - DOCKER_IMAGE_NAME=jboss4-java5
  - secure: UsjnZze4BNwA52cJA9iajw0JjghZPFYOq2x28U4GxTEa0KgBGZc9AKXkVh4opizFWdHIN3iNC2J1ofSIf6Y9XHevl4/wkMf9Fdc+jRH3pJpQl3Xku8OXh54O+7LIPr+DuBRPbxcsU8DxARsN/OJ3KVuhb5Oc01cPo8V8r8yXwmJTWbXrDARSpzgnZUni4q4PJYpaxBKxx3eC8ylk1cJTP9+vVfh+gm5e0+RhZNnTEJdl6Yy+eG0YFCwhsV29T+JrL3y26u7cGfYZx5bzcdjnTpATKAg3wefvTeyk0JXdZUA3PRhVmVpb4W5Kppu4W2eD7TOjlZgDqkSlRlH4oBMPEWspfVgsofqZalWHPa1THzaoLEJtOZ/RzB5Nl/pk8L0rQ3KonOCyR7AvEyCGtp/YDdSpIVVSzlSr8+kvBYrHWHZnPzRzKppfcjgGv/UK6PjrT/Z0Z3gTyN21kOvwitdBIC7i3qmkriyjSz9Gf+b7HnPiI7haoEeTom+lPo9WGdC1/T+9uOL6lDc8wm0PiYv8762o6JQ9W/zidyRxlKGXBhQwrYoYU1VjhDIVkrPFSzlbClePGnL0C6X8gC6sCfjtnfBWQmlTcfhQKDDrL8wsqxa/K1kajfETNnSYOOH247hR7VRGaU6t2uAG1ImRoCv8vkxpu2dE8BtTN6NQllFABpA=
script:
- docker build -t ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} .
- |
  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:latest
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:alpine
  else
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}
    docker tag ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}-alpine
  fi
- docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
- docker push ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}

